Repository CSC510-Group-25/feature-hunt, pull requests merged in 2021-11, with the labels that each got.

#85 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#92 group25 tests
  package.json
  src/App.test.js
  src/Components/Dashboard.js
  src/Components/Feature.js
  src/Components/Header.js
  src/Components/Home.js
  src/Components/Login.js
  src/Components/Product.js
  src/Components/ProductTile.js
  src/Components/SignUp.js
  src/__tests__/Dashboard.tests.js
  src/__tests__/Feature.tests.js
  src/__tests__/Feedback.tests.js
  src/__tests__/Header.tests.js
  src/__tests__/Home.tests.js
  src/__tests__/Login.tests.js
  src/__tests__/Product.tests.js
  src/__tests__/ProductTile.tests.js
  src/__tests__/SignUp.tests.js
Labels: frontend, test

#126 Restore deleted backend files
  backend/Dockerfile
  backend/app/__init__.py
  backend/app/controllers/__init__.py
  backend/app/controllers/auth_controller.py
  backend/app/controllers/products.py
  backend/app/dist/404.html
  backend/app/dist/index.html
  backend/index.py
  backend/linter.py
  backend/logger/__init__.py
  backend/logger/logger.py
  backend/requirements.txt
  backend/start_server.sh
Labels: bug, backend

#127 Create proj2rubric.md
  docs/proj2rubric.md
Labels: documentation

#135 group25 documentation
  docs/db-setup-screenshots/Screenshot 2021-11-03 feature hunt collections.png
  docs/db-setup-screenshots/Screenshot 2021-11-03 feature hunt product.png
  docs/db-setup-screenshots/Screenshot 2021-11-03 product closeup.png
  docs/db-setup-screenshots/Screenshot 2021-11-03 users.png
  docs/group25-tools/Screenshot 2021-11-03 installed apps.png
  docs/group25-tools/Screenshot 2021-11-03 tools.png
Labels: documentation

#148 Submit project form
  .idea/.gitignore
  .idea/feature-hunt.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend-new/db_init.py
  package.json
  src/App.js
  src/Components/Header.js
  src/Components/ProjectForm.js
  src/Service.js
  src/__tests__/Header.tests.js
  src/__tests__/ProjectForm.tests.js
  test/test_submit_project.py
Labels: enhancement, frontend

#158 temp fix for heroku issues
  backend/app.py
  src/Service.js
  test/test_config.py
Labels: bug

#159 group25 test submit project
  .idea/feature-hunt.iml
  backend/auth_controller.py
  backend/product_controller.py
  src/Components/Comments.js
  src/Components/Dashboard.js
  src/Components/Feature.js
  src/Components/Feedback.js
  src/Components/Header.js
  src/Components/Home.js
  src/Components/Login.js
  src/Components/Product.js
  src/Components/ProductTile.js
  src/Components/ProjectForm.js
  src/Components/SignUp.js
  src/__tests__/Header.tests.js
  src/__tests__/ProjectForm.tests.js
  test/test_product_controller.py
  test/test_user_auth.py
Labels: documentation, enhancement, frontend
